---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(reticulate)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#put your file in folder solutions, use this to access data
#this needs to de done in any chunk that access the folder
setwd('../data')
getwd()
```

```{python}
import os
os.chdir('../data')
print(os.getcwd())
```

```{python}
import os

os.chdir('../data')
#trainfolder = "C:\\Users\\cgn31\\OneDrive\\Documents\\GitHub\\STA380\\data\\ReutersC50\\C50train"  
#testfolder = "C:\\Users\\cgn31\\OneDrive\\Documents\\GitHub\\STA380\\data\\ReutersC50\\C50test"
trainfolder = "ReutersC50\\C50train"  
testfolder = "ReutersC50\\C50test"
Names = [name for name in os.listdir(trainfolder)]
trainAuthorFolder = [trainfolder + '\\' + name + "\\" for name in Names]

print trainAuthorFolder
```

This works for entries without quotation marks, need to strip before read_csv:

```{python}
import pandas as pd
import glob

os.chdir('../data')

trainList = []

for author in trainAuthorFolder:
  try:
    files = glob.glob(author + '*.txt')
    df = pd.concat([pd.read_csv(fp, sep ='\t', header = None) for fp in files], ignore_index=True, axis = 1)
    trainList.append(df)
  except:
    trainList.append("has quotation mark")
```

```{python}
for potentialFrame in trainList:
  print type(potentialFrame)
```

Example, read last df of loop into R

```{r}
frame <- py$df
```
