---
title: "Henson Q4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

With Added Noise to counts:

```{r}
social_marketing = read.csv("../data/social_marketing.csv", header = TRUE, row.names = 1)
```

```{r}
social_marketing = social_marketing + .0025
social_marketing = social_marketing / rowSums(social_marketing)
social_marketing = social_marketing * 100
```

```{r}
library(proxy)
```

```{r}
cosine_dist_mat = proxy::dist(as.matrix(social_marketing), method='cosine')
tree = hclust(cosine_dist_mat)
```

```{r}
clust_num = 15
clust = cutree(tree, k = clust_num)
```

```{r}
for (i in 1:clust_num){
  assign(paste('cluster', i, sep = '_'), colMeans(social_marketing[which(clust == i),]))
}
```

```{r}
means = data.frame(do.call(rbind, mget(ls(pattern="^cluster\\_\\d+"))))
#means = means * 100
```

```{r}
means[ apply(means, 1, max) > 20, ]
```


```{r}
means[ apply(means, 1, max) < 15, ]
```

```{r}
means[means$health_nutrition < 1.5,]
```

```{r}
means[means$personal_fitness < 1.25,]
```

```{r}
for (i in 1:clust_num){
  len = length(which(data.frame(clust)$clust == i))
  cat("Cluster", i, "has" , len, "members\n")
}

```


############################################################################


Without added noise to counts:

```{r}
social_marketing = read.csv("../data/social_marketing.csv", header = TRUE, row.names = 1)
```

```{r}
social_marketing = social_marketing / rowSums(social_marketing)
social_marketing = social_marketing * 100
```

```{r}
library(proxy)
```

```{r}
cosine_dist_mat = proxy::dist(as.matrix(social_marketing), method='cosine')
tree = hclust(cosine_dist_mat)
```

```{r}
clust_num = 15
clust = cutree(tree, k = clust_num)
```

```{r}
for (i in 1:clust_num){
  assign(paste('cluster', i, sep = '_'), colMeans(social_marketing[which(clust == i),]))
}
```

```{r}
means = data.frame(do.call(rbind, mget(ls(pattern="^cluster\\_\\d+"))))
#means = means * 100
```

```{r}
means[ apply(means, 1, max) > 20, ]
```


```{r}
means[ apply(means, 1, max) < 15, ]
```

```{r}
means[means$health_nutrition < 1.5,]
```

```{r}
means[means$personal_fitness < 1.25,]
```

```{r}
for (i in 1:clust_num){
  len = length(which(data.frame(clust)$clust == i))
  cat("Cluster", i, "has" , len, "members\n")
}

```

