---
title: "Q2 - ABIA_final"
output: html_document
---

```{r, warning=FALSE, message = FALSE}
library("tidyverse")
ABIA <- read.csv("C:/Users/tsblo/Predictive modeling/Scott_take_home/ABIA.csv")
View(ABIA)
```

```{r}
ABIA$date <- as.Date(with(ABIA, paste(Year, Month, DayofMonth,sep="-")), "%Y-%m-%d")
```

```{r, warning=FALSE, message = FALSE}
theme_set(theme_classic())
g <- ggplot(ABIA, aes(x=(UniqueCarrier), DepDelay))
g + geom_boxplot(fill="plum", outlier.shape = NA) + 
  scale_y_continuous(limits = quantile(ABIA$DepDelay, c(0.1, 0.9))) +
    labs(title="Box plot", 
         subtitle="Dep Delay grouped by Carrier",
         caption="Source: ABIA",
         x="Carrier",
         y="Departure Delay")
```
Most of the carriers's flights depart on average on or before the scheduled departure time. 
```{r, warning=FALSE, message = FALSE}
theme_set(theme_classic())
g <- ggplot(ABIA, aes(UniqueCarrier, DepDelay))
g + geom_violin(fill="plum", outlier.shape = NA) + 
  scale_y_continuous(limits = quantile(ABIA$DepDelay, c(0.1, 0.9))) +
    labs(title="Violin plot", 
         subtitle="Dep Delay grouped by Carrier",
         caption="Source: ABIA",
         x="Carrier",
         y="Departure Delay")
```
The violin plot shows that some carriers are stingy when it comes to when the flight departs. Carriers OH and YV like their flights to depart right on time instead of early.
```{r}

```
```{r}

```
```{r}

```
```









